version: '2'
services:
  mysql:
    build: mysql
    env_file:
      - envs/common.env
    volumes:
      - ./data/envs:/envs
      - ./data/moodle-mysql:/var/lib/mysql
    #entrypoint: ["sh", "-c", "sleep 2073600"]
  moodle:
    build: moodle
    links:
      - mysql
    env_file:
      - envs/common.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/envs:/envs
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/moodle-moodledata:/var/moodledata
