#!/bin/bash
mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOF

CREATE DATABASE IF NOT EXISTS moodle;

CREATE USER IF NOT EXISTS 'moodle'@'%'
IDENTIFIED BY '${MOODLE_PASSWORD}';

GRANT ALL PRIVILEGES ON moodle.* TO 'moodle'@'%';

FLUSH PRIVILEGES;
EOF